name: env-secrets

on:
  workflow_dispatch:    # allows manual run from Actions tab

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    # Bind this job to the "production" environment
    environment:
      name: production
      url: https://example.com   # just a demo URL for display (deploy it to this url)

    steps:
      - name: Print environment name
        run: echo "Environment is:${{ job.environment }}" # refers to the env specified inside the job: production

      - name: Use PROD_API_KEY
        run: echo "Prod API key is:${{ secrets.PROD_API_KEY }}"
